services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"

  api:
    build: ./api
    ports:
      - "7071:80"
    environment:
      AzureWebJobsStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KkM1bX5bXMb==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
      FUNCTIONS_WORKER_RUNTIME: "node"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - azurite

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      VITE_API_TARGET: "http://api:80"
    depends_on:
      - api
